<?php
	
	$stages = [
		'Commencement' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "BOM Finalized",
		],
		'BOM Finalized' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "Under Negotiation",
		],
		'Under Negotiation' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "PO Placed",
		],
		'PO Placed' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "Advance Sent",
		],
		'Advance Sent' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "Awaiting OC",
		],
		'Awaiting OC' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   => "Shipment ready for pickup",
		],
		'Shipment ready for pickup' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> false,
			'discardable' 	=> true,
			'pricechange' 	=> false,
			'qtychange' 	=> false,
			'isfinal'		=> false,
			'next' 	  		=> "In Transit",
		],
		'In Transit' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "In Customs",
		],
		'In Customs' => [
			'editable' 		=> true,
			'cancelable'	=> true,
			'addItem'		=> true,
			'removeItem'	=> true,
			'discardable' 	=> true,
			'pricechange' 	=> true,
			'qtychange' 	=> true,
			'isfinal'		=> false,
			'next' 	   		=> "Shipment Received",
		],
		'Shipment Received' => [
			'editable' 		=> false,
			'cancelable'	=> false,
			'discardable' 	=> false,
			'addItem'		=> false,
			'removeItem'	=> false,
			'pricechange' 	=> false,
			'qtychange' 	=> false,
			'isfinal'		=> true,
			'next' 	   		=> "",
		],
		'Canceled' => [
			'editable' 		=> false,
			'cancelable'	=> false,
			'discardable' 	=> false,
			'addItem'		=> false,
			'removeItem'	=> false,
			'pricechange' 	=> false,
			'qtychange' 	=> false,
			'isfinal'		=> true,
			'next' 	   		=> "",
		]
	];